lane :bump_version do |options|
  # Read the current version from pubspec.yaml
  pubspec_path = "../pubspec.yaml"
  pubspec_content = File.read(pubspec_path)
  version_match = pubspec_content.match(/version:\s*([0-9]+\.[0-9]+\.[0-9]+)\+([0-9]+)/)
  unless version_match
    UI.error("Failed to extract version from pubspec.yaml")
    next
  end
  
  current_version = version_match[1]
  current_build = version_match[2].to_i

  # Determine if we're bumping major, minor, or patch and need to reset the build number
  if ['major', 'minor', 'patch'].include?(options[:bump])
    new_build = 0
  else
    # Assuming bump_build option is a boolean indicating if the build number should be incremented
    new_build = options[:bump_build] ? current_build + 1 : current_build
  end

  # Call your custom action or any logic to bump version and reset build number
  result = flutter_bump_version(
    bump_build: options[:bump_build],
    parts: options[:bump],
    pubspec: pubspec_path,
    new_build: new_build # Ensure your flutter_bump_version action can accept and handle this parameter
  )
  if(options[:push] || options[:bump])
    sh "git config --global user.email kiyochinh@gmail.com"
    sh "git config --global user.name Kiyo Chinh"
    sh "git config --global push.followTags true"
    sh "git add ../pubspec.yaml"
    sh 'git commit -m "[Chore] Bump version from '+result[:previous]+ ' to ' + result[:new] + '"'
    sh 'git tag -a v'+result[:new]+' -m "Version '+result[:new]+'"'
    sh 'git pull --rebase origin '+options[:branch]
    sh "git push origin HEAD:"+options[:branch]
  end
end