default_platform(:android)

platform :android do

  desc "Submit a new build to Google Play"
  lane :deploy do |options|
    sh "flutter pub get"
    sh "flutter build appbundle -v"
    upload_to_play_store(
      track: options[:track] || "staging",
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
      )
  end

  desc "Promote from track to another track"
  lane :promote do |options|
    upload_to_play_store(
      track: options[:from] || "staging",
      track_promote_to: options[:to] || "staging",
      skip_upload_changelogs: true,
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
      version_name: options[:version_name],
      version_code: options[:version_code].to_i,
      )
  end
end
